import type { OutputGroup } from '@aws-sdk/client-mediaconvert';

export const hls = (bucketDestination: string): OutputGroup => ({
  Name: 'HLS',
  Outputs: [
    {
      NameModifier: '_hls',
      ContainerSettings: {
        Container: 'M3U8',
        M3u8Settings: {
          AudioFramesPerPes: 4,
          PcrControl: 'PCR_EVERY_PES_PACKET',
          PmtPid: 480,
          PrivateMetadataPid: 503,
          ProgramNumber: 1,
          PatInterval: 0,
          PmtInterval: 0,
          VideoPid: 481,
          AudioPids: [
            482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494,
            495, 496, 497, 498,
          ],
        },
      },
      VideoDescription: {
        ScalingBehavior: 'DEFAULT',
        Width: 854,
        Height: 480,
        TimecodeInsertion: 'DISABLED',
        AntiAlias: 'ENABLED',
        Sharpness: 100,
        AfdSignaling: 'NONE',
        DropFrameTimecode: 'ENABLED',
        RespondToAfd: 'NONE',
        ColorMetadata: 'INSERT',
        CodecSettings: {
          Codec: 'H_264',
          H264Settings: {
            InterlaceMode: 'PROGRESSIVE',
            ParNumerator: 1,
            NumberReferenceFrames: 3,
            Syntax: 'DEFAULT',
            GopClosedCadence: 1,
            HrdBufferInitialFillPercentage: 90,
            GopSize: 3,
            Slices: 1,
            GopBReference: 'ENABLED',
            HrdBufferSize: 4000000,
            MaxBitrate: 2000000,
            SlowPal: 'DISABLED',
            ParDenominator: 1,
            SpatialAdaptiveQuantization: 'ENABLED',
            TemporalAdaptiveQuantization: 'ENABLED',
            FlickerAdaptiveQuantization: 'ENABLED',
            EntropyEncoding: 'CABAC',
            RateControlMode: 'QVBR',
            QvbrSettings: {
              QvbrQualityLevel: 7,
            },
            CodecProfile: 'HIGH',
            Telecine: 'NONE',
            MinIInterval: 0,
            AdaptiveQuantization: 'MEDIUM',
            CodecLevel: 'AUTO',
            FieldEncoding: 'PAFF',
            SceneChangeDetect: 'ENABLED',
            QualityTuningLevel: 'SINGLE_PASS_HQ',
            UnregisteredSeiTimecode: 'DISABLED',
            GopSizeUnits: 'SECONDS',
            ParControl: 'SPECIFIED',
            NumberBFramesBetweenReferenceFrames: 5,
            RepeatPps: 'DISABLED',
            DynamicSubGop: 'ADAPTIVE',
          },
        },
      },
      AudioDescriptions: [
        {
          AudioTypeControl: 'FOLLOW_INPUT',
          AudioSourceName: 'Audio Selector 1',
          CodecSettings: {
            Codec: 'AAC',
            AacSettings: {
              AudioDescriptionBroadcasterMix: 'NORMAL',
              Bitrate: 64000,
              RateControlMode: 'CBR',
              CodecProfile: 'HEV1',
              CodingMode: 'CODING_MODE_2_0',
              RawFormat: 'NONE',
              SampleRate: 48000,
              Specification: 'MPEG4',
            },
          },
          LanguageCodeControl: 'FOLLOW_INPUT',
          AudioType: 0,
        },
      ],
    },
  ],
  OutputGroupSettings: {
    Type: 'HLS_GROUP_SETTINGS',
    HlsGroupSettings: {
      ManifestDurationFormat: 'INTEGER',
      SegmentLength: 10, // 10s length
      TimedMetadataId3Period: 10,
      CaptionLanguageSetting: 'OMIT',
      Destination: `s3://${bucketDestination}`,
      TimedMetadataId3Frame: 'PRIV',
      CodecSpecification: 'RFC_4281',
      OutputSelection: 'MANIFESTS_AND_SEGMENTS',
      ProgramDateTimePeriod: 600,
      MinSegmentLength: 0,
      DirectoryStructure: 'SINGLE_DIRECTORY',
      ProgramDateTime: 'EXCLUDE',
      ManifestCompression: 'NONE',
      ClientCache: 'ENABLED',
      StreamInfResolution: 'INCLUDE',
    },
  },
});

export const dash = (bucketDestination: string): OutputGroup => ({
  Name: 'DASH',
  Outputs: [
    {
      NameModifier: '_dash',
      ContainerSettings: {
        Container: 'MPD',
        MpdSettings: {},
      },
      VideoDescription: {
        ScalingBehavior: 'DEFAULT',
        Width: 854,
        Height: 480,
        TimecodeInsertion: 'DISABLED',
        AntiAlias: 'ENABLED',
        Sharpness: 100,
        AfdSignaling: 'NONE',
        DropFrameTimecode: 'ENABLED',
        RespondToAfd: 'NONE',
        ColorMetadata: 'INSERT',
        CodecSettings: {
          Codec: 'H_264',
          H264Settings: {
            InterlaceMode: 'PROGRESSIVE',
            ParNumerator: 1,
            NumberReferenceFrames: 3,
            Syntax: 'DEFAULT',
            GopClosedCadence: 1,
            HrdBufferInitialFillPercentage: 90,
            GopSize: 3,
            Slices: 1,
            GopBReference: 'ENABLED',
            HrdBufferSize: 4000000,
            MaxBitrate: 2000000,
            SlowPal: 'DISABLED',
            ParDenominator: 1,
            SpatialAdaptiveQuantization: 'ENABLED',
            TemporalAdaptiveQuantization: 'ENABLED',
            FlickerAdaptiveQuantization: 'ENABLED',
            EntropyEncoding: 'CABAC',
            RateControlMode: 'QVBR',
            QvbrSettings: {
              QvbrQualityLevel: 7,
            },
            CodecProfile: 'HIGH',
            Telecine: 'NONE',
            MinIInterval: 0,
            AdaptiveQuantization: 'MEDIUM',
            CodecLevel: 'AUTO',
            FieldEncoding: 'PAFF',
            SceneChangeDetect: 'ENABLED',
            QualityTuningLevel: 'SINGLE_PASS_HQ',
            UnregisteredSeiTimecode: 'DISABLED',
            GopSizeUnits: 'SECONDS',
            ParControl: 'SPECIFIED',
            NumberBFramesBetweenReferenceFrames: 5,
            RepeatPps: 'DISABLED',
            DynamicSubGop: 'ADAPTIVE',
          },
        },
      },
      AudioDescriptions: [
        {
          AudioTypeControl: 'FOLLOW_INPUT',
          AudioSourceName: 'Audio Selector 1',
          CodecSettings: {
            Codec: 'AAC',
            AacSettings: {
              AudioDescriptionBroadcasterMix: 'NORMAL',
              Bitrate: 64000,
              RateControlMode: 'CBR',
              CodecProfile: 'HEV1',
              CodingMode: 'CODING_MODE_2_0',
              RawFormat: 'NONE',
              SampleRate: 48000,
              Specification: 'MPEG4',
            },
          },
          LanguageCodeControl: 'FOLLOW_INPUT',
          AudioType: 0,
        },
      ],
    },
  ],
  OutputGroupSettings: {
    Type: 'DASH_ISO_GROUP_SETTINGS',
    DashIsoGroupSettings: {
      SegmentLength: 10, // 10s length
      FragmentLength: 2,
      Destination: `s3://${bucketDestination}`,
    },
  },
});
